### ISSUE TITLE
Allow use of self signed certificates

### ISSUE THREAD

**Issue by pasmon** [fbernitt/hubot-gocd#3]
Our Go.CD is behind HTTPS, configured with self signed certificate, and this prevents Hubot to access the cctray.xml:

> Failed to fetch data from https://go.example.com/go/cctray.xml with error : Error: self signed certificate

**Comment by fbernitt** [comment]
Just as a quick fix: Would it be possible to use [let's encrypt](https://letsencrypt.org/) and use a valid certificate?

**Comment by pasmon** [comment]
I don't think it's possible since our server is not reachable from internet. Some days ago I tried let's encrypt and couldn't produce certificates from our intranet.

**Comment by fbernitt** [comment]
I pushed support for https related flags like custom CA file and disable tls validation if you want to take that risk. Could you give it a try? If it works I'll prepare a new release.

**Comment by pasmon** [comment]
Sure I can try, any advice on how to test it? I've only used the NPMs as Hubot scripts.

**Comment by pasmon** [comment]
BTW, in the NPM page there's this variable:
HUBOT_GITHUB_EVENT_NOTIFIER_ROOM="#roomname"

I think it should be:
HUBOT_GOCI_EVENT_NOTIFIER_ROOM="#roomname"

**Comment by fbernitt** [comment]
Ah, it should work if you just replace the content of the node_modules/hubot-gocd/src/scripts/gocd.coffee file with the latest version [gocd.coffe](https://raw.githubusercontent.com/fbernitt/hubot-gocd/master/src/scripts/gocd.coffee).

**Comment by pasmon** [comment]
Hmm, I thought I had to restart Hubot service in order to use the new version but that just overwrote the modified file. Now that I didn't restart Hubot, it seems that Hubot got the build details from our Go.CD. :+1: 

I only tested with TLS validation disabled.

**Comment by fbernitt** [comment]
Thanks, new version v0.0.6 is now published. The variable on the NPM page has also been renamed to HUBOT_GOCI_EVENT_NOTIFIER_ROOM.
